openapi: 3.0.3
paths:
  /sensors/create:
    post:
      description: Создание датчика
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSensorRequest'
        required: true
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorIdResponse'
        '400':
          $ref: '#/components/responses/BadRequest'

  /sensors/update:
    post:
      description: Редактирование датчика по ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSensorRequest'
        required: true
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorIdResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /sensors:
    get:
      description: Получение списка всех датчиков или информации о конкретном датчике по ID
      parameters:
        - name: id
          in: query
          required: false
          description: (опционально) ID запрашиваемого датчика. Если указан, возвращается информация только о данном датчике.
          schema:
            type: string
      responses:
        '200':
          description: Успешно получен список датчиков или информация о конкретном датчике
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorsResponse'
        '204':
          description: Датчики не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /sensors/trigger:
    post:
      description: Срабатывание датчика для создания тикета
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TriggerSensorRequest'
        required: true
      responses:
        '200':
          description: Успешно создан тикет
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketIdResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    BaseSensor:  # Общая структура для создания/обновления датчиков
      type: object
      required:
        - ticketTitle
        - ticketDescription
        - ticketPriority
        - ticketDeadline
        - businessProcessId
      properties:
        ticketTitle:
          type: string
          description: Название тикета
        ticketDescription:
          type: string
          description: Описание тикета
        ticketPriority:
          $ref: '#/components/schemas/Priority'
        ticketDeadline:
          $ref: '#/components/schemas/Deadline'
        businessProcessId:
          type: string
          description: ID бизнес процесса

    CreateSensorRequest:
      allOf:
        - $ref: '#/components/schemas/BaseSensor'

    UpdateSensorRequest:
      allOf:
        - $ref: '#/components/schemas/BaseSensor'
        - type: object
          required:
            - id
          properties:
            id:
              type: string
              description: ID редактируемого датчика

    SensorIdResponse:
      type: object
      required:
        - sensorId
      properties:
        sensorId:
          type: string
          description: ID датчика

    TicketIdResponse:
      type: object
      required:
        - ticketId
      properties:
        ticketId:
          type: string
          description: ID созданного тикета

    TriggerSensorRequest:
      type: object
      required:
        - sensorId
      properties:
        sensorId:
          type: string
          description: ID датчика, который сработал

    SensorsResponse:
      type: object
      required:
        - sensors
      properties:
        sensors:
          type: array
          items:
            $ref: '#/components/schemas/SensorResponse'

    SensorResponse:
      allOf:
        - $ref: '#/components/schemas/BaseSensor'
        - type: object
          required:
            - id
          properties:
            id:
              type: string
              description: ID датчика

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Описание ошибки

    Priority:
      type: string
      description: Приоритет тикета
      enum:
        - High
        - Medium
        - Low

    Deadline:
      type: string
      format: date-time
      description: Дедлайн для тикета

  responses:
    BadRequest:
      description: Неверные данные
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'